version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
  pre_build:
    commands:
      - ls -al
      - mkdir dist
      - rsync -av --exclude='appspec.yml' --exclude='awsscripts/aws_codedeploy_config.sh' --exclude='awsscripts/install_dependencies.sh' --exclude='awsscripts/start_application.sh' --exclude='awsscripts/stop_application.sh' ./* dist
artifacts:
  files:
      - '**/*'
base-directory: mifosFrontend
discard-paths: yes
