version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
  pre_build:
    commands:
      - ls -al     
artifacts:
  files:
      - app/*
discard-paths: yes
