version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
      - npm install rubygems
      - gem sources -a http://rubygems.org
      - gem install bundler
      - bundle install
  pre_build:
    commands:
      - tar -cvf dist.tar .
      - mkdir dist
      - tar -xvf dist.tar -C dist
      - ls -al
      - grunt prod
      - ls -al
artifacts:
  files:
      - dist/**/*
      - awsscripts/install_dependencies.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml
base-directory: mifosFrontend     
discard-paths: yes
