version: 0.1
phases:
  build:
    commands:
      - rm -rf node_modules dist
      - npm install -g bower && npm install -g grunt-cli && bower install --allow-root && npm install -g @angular/cli && npm install --save-dev @angular/cli@latest && rm -rf package-lock.json && npm install
      - ls -al
artifacts:
  files:
    - dist/*
discard-paths: yes
