version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install
      - npm install
  build:
    commands:
      - ng build --target=production
artifacts:
  files:
    - dist/*
discard-paths: yes
