version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install -g @angular/cli
      - npm install
  pre_build:
    commands:
      - ls -al
  build:
    commands:
      - ng build --target=production
artifacts:
  files:
    - dist/*
discard-paths: yes
