version: 0.1
phases:
  build:
    commands:
      - npm install -g @angular/cli && npm install -g bower && npm install -g grunt-cli && bower install && npm install && ng build --target=production
artifacts:
  files:
    - dist/*
discard-paths: yes
