version: 0.1
phases:
  install:
    commands:
      - npm install -g bower
      - npm install -g grunt-cli
      - bower install --allow-root
      - npm install --save-dev @angular/cli@latest
  pre_build:
    commands:
      - ls -al
artifacts:
  files:
      - awsscripts/install_dependencies.sh
      - awsscripts/start_application.sh
      - awsscripts/stop_application.sh
      - awsscripts/aws_codedeploy_config.sh
      - appspec.yml
      - .bowerrc
      - .git/*
      - .gitignore
      - .jshintrc
      - .project
      - .travis.yml
      - Contributing.md
      - Gruntfile.js
      - LICENSE.txt
      - README.md
      - UIconfig.json
      - app/*
      - bower.json
      - build.gradle
      - build.sh
      - buildspec.yml
      - gems.rb
      - karma-e2e.conf.js
      - karma.conf.js
      - node_modules/*
      - package.json
      - release.sh
      - test/*
discard-paths: yes
